### ISSUE TITLE
Correct combinations of search filter parameters for book appointment

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#100]
1.  Check that the demonstrator correctly can receive all combinations of search filter passed to search for free slots at:

https://nhsconnect.github.io/gpconnect/appointments_slotavailabilitymanagement.html#appointment-availability-control

(i.e. no search filter, search filter with org type, search filter with ODS code, search filter with org type and ODS code)

Note - the demonstrator may already do this.

---
In line with 1.2.1 release note

**Comment by SimonFarrowNHS** [comment]
Hi Russell

There doesn't appear to be a test for this.

**Comment by SimonFarrowNHS** [comment]
Inspection of the code suggests that this copmbination is catered for

**Comment by SimonFarrowNHS** [comment]
Have created an issue in the provider project for these new tests
