### ISSUE TITLE
MedicationRequest resource

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#102]
1.  Amend dispenseRequest.validityPeriod element population in line with:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_medicationrequest.html#dispenserequestvalidityperiod

2. Amend status element population guidance in line with:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_medicationrequest.html#status

3. Ensure amendment reason is populated in statusReason.reason, not in detectedIssue:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_medication_guidance.html#amendments

---
Changes in line with 1.2.1 release note https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
