### ISSUE TITLE
MedicationStatement resource

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#103]
1. Clarification on PrescribingAgency

Ensure this element is populated in line with:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_medicationstatement.html#extensionprescribingagency

2. Amend status element population guidance

Ensure this element is populated in line with:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_medicationstatement.html#status

3. Amend effective (period) element population guidance

Ensure this element is populated in line with:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_medicationstatement.html#effective

---
In line with 1.2.1 release note
https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#access-record-structured

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
