### ISSUE TITLE
List resource

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#104]
1. Correct ‘General practice services’ to ‘General practice service’ for extension[clinicalSetting] element in line with SNOMED term

2. Ensure 'data awaiting filing' is not returned (if the demonstrator was returning this).

---
In line with 1.2.1 release note at https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
