### ISSUE TITLE
Degraded medications

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#105]
Ensure the demonstrator is returning some degraded medications in its return payload, in line with:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_medication_guidance.html#degraded-medications

---
In line with 1.2.1 release note https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html

**Comment by SimonFarrowNHS** [comment]
Patient 12 already has degraded medications
