### ISSUE TITLE
Add representative clinical data to the demonstrator

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#106]
Placeholder note for now, while clinical data is produced by Pete and colleagues.

**Comment by RiChallinor** [comment]
@jonnyry to speak to @PeteSalis

**Comment by jonnyry** [comment]
Email sent to @PeteSalis

**Comment by SimonFarrowNHS** [comment]
After discussion with Jonnyr we have decided to close this long running rather general issue. We now have a regular weekly meeting with PeteSalis on this topic. Other more specific lower level items will be raised, and addressed,  as and when they occur.
