### ISSUE TITLE
Structured $gpc.getcarerecord Medication.code - no code or display present

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/gpconnect-demonstrator#111]
The Medications in the bundle don't have code or display present, system is present as is an extension containing code and display.

e.g.

'''
{
“resource”: {
“resourceType”: “Medication”,
“id”: “12”,
“meta”: {
“profile”: [
“https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Medication-1”
]
},
“code”: {
“coding”: [
{
“extension”: [
{
“url”: “https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-coding-sctdescid”,
“extension”: [
{
“url”: “descriptionId”,
“valueId”: “19524811000001103"
},
{
“url”: “descriptionDisplay”,
“valueString”: “Povidone-iodine 5% cream”
}
]
}
],
“system”: “http://snomed.info/sct”
}
]
}
}
},
'''

This doesn't match https://developer.nhs.uk/apis/gpconnect-1-2-1/pages/accessrecord_structured/guidance-on-the-population-of-codeableconcept.pdf

**Comment by KevinMayfield** [comment]
Copied over from https://github.com/nhsconnect/gpconnect/issues/569

**Comment by PeteSalis** [comment]
@KevinMayfield would you be able to let us know which patient the demonstrator was returning in this case?

**Comment by KevinMayfield** [comment]
Mike Meakin 9658218873

It would be ideal if this could be resolved before the INTEROPen connectathon (as we are suggesting Mike is Micheal from Micheal's Storey)

**Comment by SimonFarrowNHS** [comment]
Started looking at this and noticed that the examples at 
https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_fhir_examples_medication.html
have DescriptionID and DescriptionDisplay but  other parts of spec refer to these items with an initial lower case d.

**Comment by SimonFarrowNHS** [comment]
I can move the code to coding.code and the description to coding.display as suggested.
The db does not currently have values for description id.
Can I just remove the descriptionID and descriptionDisplay extensions? As now they don't carry any useful extra data?

**Comment by SimonFarrowNHS** [comment]
Gents if you really need this in for the cop this Thursday then you need to give me some guidance.

**Comment by KevinMayfield** [comment]
If it's any help. This page shows both GP Connect and Care Connect MedicationStatements alongside each other. https://data.developer.nhs.uk/ccri/ed/patient/1183

Clicking on the syringe will show the Medication - the <> icons will get you to the FHIR resource. (I might have moved the descriptionId to code)

**Comment by SimonFarrowNHS** [comment]
After discussion with Pete Salisbury none of the codes is a description. If one was it has a penultimate digit of 1. So we can drop the redundant extensions.
