### ISSUE TITLE
Full Resources contained within a List

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/gpconnect-demonstrator#112]
Not sure if this is by design in GP Connect.

Full resources are being contained in Lists 
e.g. 

For Patient  NHS No: 9658218873

 "contained": [
                    {
                        "resourceType": "AllergyIntolerance",
                        "id": "27",
                        "meta": {

This is a complete resource, a general FHIR rule/convention is: contained should only be used for partial resources and the list should reference this resource.

This is also more difficult for a developer to work with as they need to process the bundle and then process each resource in the bundle looking at the contained resources.

**Comment by KevinMayfield** [comment]
also potentially unsafe as other AllergyIntolerances are listed normally within the Bundle.

**Comment by PeteSalis** [comment]
@KevinMayfield during the Care Connect curation process it was decided that any resolved/ended allergies that are returned by a system should be returned as contained resources within a list. 

It was intended that this would minimise the risk of someone mistaking a resolved/ended allergy for an active allergy.

**Comment by KevinMayfield** [comment]
I feel is a user interface constraint which doesn't still well on a API and will lead to developers making mistakes (such as ignoring the contained Allergies because they are stored in a non standard place).

**Comment by RiChallinor** [comment]
Following review no action required.
