### ISSUE TITLE
Register Patient - PDS mismatch

### ISSUE THREAD

**Issue by privchiadzwa** [nhsconnect/gpconnect-demonstrator#120]
Amend   Demonstrator to return a relevant response for Register Patient requests   containing details of a patient whose demographic details do not match PDS.   CONS-FoundationAPITest51
--

**Comment by SimonFarrowNHS** [comment]
After some discussion with Russell we concluded this was not amenable to assurance via a changes to demonstrator/provider behaviour. Hence I am closing the issue.
