### ISSUE TITLE
Appointments -Demonstrator change request -Book Appointment- invalid description

### ISSUE THREAD

**Issue by privchiadzwa** [nhsconnect/gpconnect-demonstrator#123]
Amend   Demonstrator to return a relevant response for Book Appointment with the   contents of Appointment.description > 100 characters.   CONS-AppointmentsAPITest15
--

**Comment by SimonFarrowNHS** [comment]
This was fixed in the ;latest 1.2.1 uplift release

**Comment by SimonFarrowNHS** [comment]
This was fixed in the latest 1.2.1 uplift release
