### ISSUE TITLE
Appointments -Demonstrator change request -Book Appointment- invalid comment

### ISSUE THREAD

**Issue by privchiadzwa** [nhsconnect/gpconnect-demonstrator#124]
Amend   Demonstrator to return a relevant response for Book Appointment with the   contents of Appointment.comment > 500 characters.   CONS-AppointmentsAPITest16
--

**Comment by SimonFarrowNHS** [comment]
This was fixed in the latest 1.2.1 uplift release

**Comment by SimonFarrowNHS** [comment]
This was fixed in the latest 1.2.1 uplift release

**Comment by SimonFarrowNHS** [comment]
This was fixed in the latest 1.2.1 uplift release

**Comment by SimonFarrowNHS** [comment]
This was fixed in the latest 1.2.1 uplift release

**Comment by SimonFarrowNHS** [comment]
This was fixed in the latest 1.2.1 uplift release
