### ISSUE TITLE
CapabilityStatement - references to operations

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/gpconnect-demonstrator#127]
Reference implementation CapabilityStatement (GET /metadata) currently returns: 

  "operation": [
        {
          "name": "gpc.getstructuredrecord",
          "definition": {
            "reference": "OperationDefinition/Patient--gpc.getstructuredrecord"
          }
        },
        {
          "name": "gpc.registerpatient",
          "definition": {
            "reference": "OperationDefinition/Patient--gpc.registerpatient"
          }
        }
      ]

The references should be to 

https://fhir.nhs.uk/STU3/OperationDefinition/GPConnect-RegisterPatient-Operation-1
and 
https://fhir.nhs.uk/STU3/OperationDefinition/GPConnect-GetStructuredRecord-Operation-1
respectively

**Comment by KevinMayfield** [comment]
oops ... the other way around, not respectively

**Comment by jonnyry** [comment]
See example response in the spec:

https://nhsconnect.github.io/gpconnect/foundations_use_case_get_the_fhir_capability_statement.html#payload-response-body

`
"operation": [
        {
          "name": "gpc.registerpatient",
          "definition": {
            "reference": "https://fhir.nhs.uk/STU3/OperationDefinition/GPConnect-RegisterPatient-Operation-1"
          }
        },
        {
          "name": "gpc.getstructuredrecord",
          "definition": {
            "reference": "https://fhir.nhs.uk/STU3/OperationDefinition/GPConnect-GetStructuredRecord-Operation-1"
          }
        }
`
