### ISSUE TITLE
Demonstrator does not handle descriptionIDs

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect-demonstrator#146]
After discussing #111 with Simon Farrow it became apparent that currently the database for the demonstrator does not have separate columns for DescriptionID and ConceptID. For the moment this is not an issue as all allergy and Meds data present for structured only contains ConceptIDs.

However as we want to load more complex data then this will be a limiting factor and needs to be addressed.

**Comment by SimonFarrowNHS** [comment]
dont know how this got closed
--

**Comment by lucywilcock** [comment]
Changes to the database have been made (branch med_desc_id for merge after final 1.2.2. uplifts). No data has currently been added to these columns and no description id or display will ever be added to the Medication resource as it stands. Further changes are needed for this.

**Comment by lucywilcock** [comment]
Similar changes to allergy entity have also been made. Same restrictions apply.

**Comment by lucywilcock** [comment]
All changes have been made to branch desc_id. This has not yet been merged. It will be left until after the final 1.2.2 uplift changes have been completed before merging.

**Comment by lucywilcock** [comment]
Spoke to Pete. Description code/display columns are now available for the allergy code, allergy manifestation and the medication code. On dest_id branch.

**Comment by PeteSalis** [comment]
Would i t be useful if I came up with some data that would use the new fields? We could then export them and check that they were exporting correctly?

**Comment by lucywilcock** [comment]
@PeteSalis I've faked some (admittedly unrealistic) data for now. The JSON for an allergyIntolerance looks as below. The code has a translation and a description code. The reaction.manifestation only has the concept code. Does this look correct? If you have some more realistic data to use then it might be helpful.

{"resource":{"resourceType":"AllergyIntolerance","id":"28","meta":{"profile":["https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-AllergyIntolerance-1"]},"identifier":[{"system":"https://fhir.nhs.uk/Id/cross-care-setting-identifier","value":"f4e0027f-e1ad-11e8-a966-00155df42f90"}],"clinicalStatus":"active","verificationStatus":"unconfirmed","category":["environment"],"code":{"coding":[{"extension":[{"url":"https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-coding-sctdescid","extension":[{"url":"descriptionId","valueId":"desc"},{"url":"descriptionDisplay","valueString":"display"}]}],"system":"http://snomed.info/sct","code":"294716003","display":"Biphasic insulin allergy (disorder)"},{"system":"trans system","code":"trans code","display":"trans display","userSelected":true}]},"patient":{"reference":"Patient/2"},"onsetDateTime":"2016-05-01T12:00:00+01:00","assertedDate":"2016-06-01T12:00:00+01:00","recorder":{"reference":"Practitioner/1"},"note":[{"text":"Rash"}],"reaction":[{"manifestation":[{"coding":[{"system":"http://snomed.info/sct","code":"247472004","display":"Weal (disorder)"}]}],"description":"Rash","severity":"severe"}]}}

**Comment by lucywilcock** [comment]
Currently on branch desc_id. The codeableConcept for allergy code and manifestation and medication code are populated as above.

**Comment by lucywilcock** [comment]
Merged into develop. Closing
