### ISSUE TITLE
Demonstrator doesn't appear to support translations

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect-demonstrator#147]
The demonstrator only has one code field so does not appear to be able to support translations from legacy codes.

When a code has been input into a system as a legacy code eg. Read2 then it is common that this code will be exported along with a SNOMED translation if one exists. How to do this is detailed in our requirements for how to populate the codable concept here,

https://developer.nhs.uk/apis/gpconnect-1-2-1/pages/accessrecord_structured/guidance-on-the-population-of-codeableconcept.pdf

**Comment by SimonFarrowNHS** [comment]
dont know how this got closed

**Comment by lucywilcock** [comment]
Does this need doing for every place we record a codeable concept?

**Comment by lucywilcock** [comment]
Spoke to Pete - this should be done for allergy code and manifestation and medication code. Others can be added in later if need be

**Comment by lucywilcock** [comment]
Have added a new table for translation codes to avoid adding three new columns in multiple places. Allergy code and manifestion and medication code reference the id of the new translation table. This is added to the codeableConcept in the builder (as with description #146). Branch desc_id to avoid conflicts with #146.

**Comment by lucywilcock** [comment]
Merged into develop. Closing
