### ISSUE TITLE
AllergyIntolerance/manifestation - nullFlavor not populated correctly

### ISSUE THREAD

**Issue by PeteSalis** [nhsconnect/gpconnect-demonstrator#148]
Found in patient 9658218873

The nullFlavor is populated as,

                "coding": [
                  {
                    "system": "http://snomed.info/sct",
                    "code": "nullFlavor NI",
                    "display": "nullFlavor NI"
                  }

It should be,

                "coding": [
                  {
                    "system": "http://hl7.org/fhir/v3/NullFlavor"
                    "code": "NI",
                    "display": "No Information"I"
                  } 

As per the FHIR guidance here,

https://www.hl7.org/fhir/v3/NullFlavor/cs.html

**Comment by SimonFarrowNHS** [comment]
dont know how this got closed
--

**Comment by lucywilcock** [comment]
This is hard-coded in the demonstrator. I can change the code to match the above or I can change the database to include a manifestation so that it is possible to have other options and remove the hard-coded values.

My instinct is to go with the latter. Which is the preferred solution?

**Comment by SimonFarrowNHS** [comment]
Latter sounds more flexible.

BTW there is an  issue open around removing the end date on search for medications. #142

I know I said I would stay clear of meds but we do have a meds release coming up next week so I am intending to address that one, if that’s ok with you?

**Comment by lucywilcock** [comment]
I'll go with the latter.

Yes, that is fine. Hopefully most of my changes will be database side so we shouldn't clash.

**Comment by lucywilcock** [comment]
This data already existed in the database, changed the code to pull it in. Reaction now appears as below in the demonstrator and as 

"coding":[{
    "system":"http://snomed.info/sct",
    "code":"247472004",
    "display":"Weal (disorder)"}]
}]

This has been done in branch feature/allergy_manifestation to be merged into develop when 1.2.2 changes are complete.

![image](https://user-images.githubusercontent.com/36481827/47919802-421f0000-dea8-11e8-8276-ef87d60f00cf.png)

**Comment by lucywilcock** [comment]
Merged into develop. Closing
