### ISSUE TITLE
Appointments: AppointmentType Coding

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#157]
For several of the appointment calls the appointmentType is expected. This is not part of the FHIR [appointment resource](https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1).

This needs to be removed from both the front end and the back end of the demonstrator code base. It should be possible to read, create, amend and cancel appointments without exceptions. Any appointment resources in the request or the response should meet the GPConnect-Appointment-1 structure definition.

The database stores the coding in the fields typeCode, typeDisplay and typeText. These fields should be removed from the database. The deliveryChannel should be available via the slot. 

This was first noticed when a third party was attempting to book and then cancel an appointment without a typeCode. This causes a number format exception. A temporary fix (extra try/catch block) has been put in place in AppointmentResourceProvider.appointmentDetailToAppointmentResourceConverter (commented as temp fix only). This should be removed.

**Comment by jackiebarnes** [comment]
@jonnyry 
Appointment Type element was replaced by Specialty in the DSTU2 - STU3 uplift;  Specialty excluded from scope given clinical coding purpose of element which can't be fulfilled by Providers and also exceeds agreed IG constraints for the administrative purpose and context for Appt Mgmt API uses.

**Comment by rbutterf** [comment]
Added Scenario: Book appointment with typeCode in appointment resource should fail as typecode is not allowed in a Book Appointment

**Comment by SimonFarrowNHS** [comment]
Had removed typecode but there was no defensive code to reject incoming

**Comment by SimonFarrowNHS** [comment]
Added code to detect presence of unwanted elements
