### ISSUE TITLE
Slots: ServiceType Coding

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#158]
When performing the 'Get Free Slots' call the slot resources returned contain a serviceType coding. This is not supported in the [GP Connect Slot structure definition](https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Slot-1).

The code to add this should be removed from the back end of the demonstrator. 

The unnecessary fields should be removed from the database. Preliminary investigations reveal the fields  typeCode and typeDisplay are no longer needed. DeliverChannelCodes is still needed to populate the deliveryChannel field.

All slot resources should meet the GP Connect Slot resource criteria.

**Comment by jackiebarnes** [comment]
@jonnyry 
For info - see comment from James of 22/11/17 on https://github.com/nhsconnect/gpconnect/issues/309;  according to him, the Slot Service Type element was replaced by 'Specialty' which we removed from scope in earlier releases given the clinical coding purpose of this element
