### ISSUE TITLE
Passing no searchFilter parameters yields the error BAD_REQUEST

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-demonstrator#160]
Request to add a test to check the Provider response when the Consumer does not pass a search filter (Org Type and ODS code) as part of the Search for free slots search parameters.

In this instance the slots returned should be:
Are marked as GP Connect bookable
AND have no organisation type restriction set
AND have no organisation/organisation group restriction set

See https://nhsconnect.github.io/gpconnect/appointments_slotavailabilitymanagement.html for more info

**Comment by jonnyry** [comment]
Passing no searchFilter parameter yields the error BAD_REQUEST / “Failed to call access method”.

This is allowed and should return slots and schedules that have not been restricted to a specific organisation or organisation type.

**Comment by SimonFarrowNHS** [comment]
Under what other circs should slots which meet these criteria be returned?
eg when an ods code is specified should unassigned slots be returned?

**Comment by SimonFarrowNHS** [comment]
Added appointments between 17:00 and 18:00 on day + 1 having no org or type
