### ISSUE TITLE
Automated test pack - amend cancellation reason for a future booked appointment

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-demonstrator#161]
If the consumer attempts to amend an appointment updating the cancellation reason only for a future booked appointment (i.e. status equals booked) then an Operation Outcome should be returned

**Comment by SimonFarrowNHS** [comment]
Not Sure exactly what this means, can you clarify/add example please?

**Comment by rbutterf** [comment]
the  Amend Appointment request has an extension for "https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-AppointmentCancellationReason-1", with a reason of double booked..

The Amend Appointment should only allow an update to the description or comment fields
