### ISSUE TITLE
Demonstrator doesn't have any patients with nhsCommunication element populated

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#163]
Add patient language and interpreter required fields for some of the patients on the demonstrator.

**Comment by SimonFarrowNHS** [comment]
These details are returns as "static data" whenever a patient is registered.
Patient retrieval does not currently return this though.

**Comment by jonnyry** [comment]
OK could you add for patient search/read?  Thanks.

**Comment by SimonFarrowNHS** [comment]
That would be the general idea :-)

**Comment by SimonFarrowNHS** [comment]
Added fixed elements as discussed
