### ISSUE TITLE
Search for free slots 'searchFilter' parameter should contain the consumers ODS code, not the providers

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#166]
Passing in a searchFilter of `https://fhir.nhs.uk/Id/ods-organization-code|A20047` yields free slots when connecting to the demonstrator, however this ODS code is meant to be the consumers ODS code, and NOT the providers ODS code.

Not sure how best to resolve this - suggest we at least have some slots that aren't restricted to a consumer - then consumers will receive Slots, regardless of the ODS code passed in.

**Comment by SimonFarrowNHS** [comment]
See my comment at #160 https://github.com/nhsconnect/gpconnect-demonstrator/issues/160
Same question applies here

**Comment by SimonFarrowNHS** [comment]
This is apparently now urgent.
Spotted this useful reference https://nhsconnect.github.io/gpconnect/appointments_slotavailabilitymanagement.html
which was mentioned in #160.
We will need some provider tests to check this works.
At least two of the categories mentioned are not covered by existing demonstrator functionality

**Comment by SimonFarrowNHS** [comment]
ALgorithm updated top reflect specification. Slots.txt also amended,
