### ISSUE TITLE
Sending in a date and time value (e.g. ge2018-12-15T10:00) causes an error

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#167]
Sending in a date and time value (e.g. ge2018-12-15T10:00) causes an error:
 
INVALID_PARAMETER / “Invalid date/time used”

Though am slightly cautious over whether to fix this – as I guess the test pack doesn’t check for this, and therefore we don’t know whether providers have implemented it or not?

Suggest we check whether providers support this first.

**Comment by SimonFarrowNHS** [comment]
Looking at the code the reason this was rejected is because the time is partial ie it should be of the form 10:00:00 not 10:00 so isn't that correct behaviour?

**Comment by jonnyry** [comment]
According to the test suite, the following are valid date/times:
 
| StartDate                              | EndDate             
| yyyy-MM-dd                          | yyyy-MM-dd          
| yyyy-MM-ddTHH:mm:ssZ     | yyyy-MM-ddTHH:mm:ssZ
| yyyy-MM-dd                          | yyyy-MM-ddTHH:mm:ssZ
| yyyy-MM-ddTHH:mm:ssZ     | yyyy-MM-dd          
 
And the following are valid:
 
| StartDate                              | EndDate             
| yyyy-MM-ddTHH:mm:ss       | yyyy-MM-ddTHH:mm:ss 
| yyyy-MM-ddTHH:mm:ssZ     | yyyy-MM-ddTHH:mm:ss 
| yyyy-MM-ddTHH:mm:ss       | yyyy-MM-ddTHH:mm:ssZ
| yyyy                                       | yyyy-MM             
| yyyy-MM                               | yyyy                
 
Since the demonstrator is passing all these tests, it is working correctly and in line with the provider systems.
 
I’ll have a look at the spec, and make sure it is clearer in this regard.
