### ISSUE TITLE
Appointments - Searching for free slots with invalid start/end dates

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-demonstrator#169]
When searching for free slots the start date and end dates must be valid - 

these should fail

ie yyyy to yyyy-mm 
      <requestParameter name="start" value="ge2019" />
      <requestParameter name="end" value="le2019-01" />

and yyyy-mm to yyyy should fail 
      <requestParameter name="start" value="ge2019-01" />
      <requestParameter name="end" value="le2019" />

**Comment by SimonFarrowNHS** [comment]
Amended the relevant regexp
