### ISSUE TITLE
Remove Schedule and Medication endpoint

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#183]
The 1.2.2 demonstrator appears to have /Schedule and /Medication endpoints in it (possibly hanging around from when we were considering supporting these endpoints).

In the interests of keeping in line with the spec, it would be good to get these two removed, as they are not supported in the current version of the spec.

**Comment by SimonFarrowNHS** [comment]
These services have been removed and the CapabilityStatement is now populated from a json template instead of being derived.
