### ISSUE TITLE
Book appointment - the practitioner role returned does not correspond with that in the matching schedule

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#195]
When booking an appointment, the practitioner role element returned appears to be a fixed value - it should match the practitioner role in the matching Schedule (linked to the Slot that was booked):

(also the R0050 role is not part of the GPConnect-PractitionerRole-1 valueset, though this is probably not too relevant if the above issue is fixed.)

```
    {
      "url": "https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-PractitionerRole-1",
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "https://fhir.nhs.uk/STU3/ValueSet/GPConnect-PractitionerRole-1",
            "code": "R0050",
            "display": "Consultant"
          }
        ]
      }
    }
```

**Comment by SimonFarrowNHS** [comment]
This information is now derived from the schedule not the practitioner table
