### ISSUE TITLE
Retrieve patient appointments does not contain the contained organisation that is sent at the time of booking

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#197]
A contained booking organisation is sent at the time of booking an appointment, this should be returned contained in the appointment resource when Read Appointment or Retrieve Patient Appointments is called:

https://nhsconnect.github.io/gpconnect/appointments_use_case_retrieve_a_patients_appointments.html
https://nhsconnect.github.io/gpconnect/appointments_use_case_read_an_appointment.html

**Comment by SimonFarrowNHS** [comment]
Suspect this is due to the org not being supplied on book. Validation to added for this mandatory element as part of a wider issue to be raised on tightening up book/amend/cancel appointment validation

**Comment by jonnyry** [comment]
This is most likely linked to https://github.com/nhsconnect/gpconnect-demonstrator/issues/203

**Comment by SimonFarrowNHS** [comment]
This is now subsumed into #203
