### ISSUE TITLE
Book appointment - contained organisation telecom overwrites the type and use element

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#198]
Sending the following in the booking organisation:

```
      "telecom": [
        {
          "system": "email",
          "value": "aa@aaa.com"
        },
        {
          "system": "phone",
          "value": "0113 258 256911",
          
        }
      ]
```

returns the following in the response:

```
      "telecom": [
        {
          "system": "phone",
          "value": "aa@aaa.com",
          "use": "temp"
        }
      ]
```

I think it's OK for us to support just one telecom value for a contained booking organisation, however I would do something like the following:

- When reading the telecoms grab the first one matching "phone" and store/return this.
- Either don't populate "use" in the response, or ensure the "use" is carried over from what was passed in

**Comment by SimonFarrowNHS** [comment]
Demonstrator now persists one instance (system and use are also now persisted)  if there's more than one it picks phone, if present, otherwise just the first occurrence.
