### ISSUE TITLE
Amend appointment - amending a cancelled appointment is no longer allowed

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#199]
In line with spec change:

https://github.com/nhsconnect/gpconnect/issues/601

Amending a cancelled appointment is no longer allowed.

If an appointment with a status of cancelled is amended, the demonstrator should return a 422 / INVALID_RESOURCE error.

Cancellation reason can no longer be amended (as this could only be amended when the appointment was cancelled).

**Comment by SimonFarrowNHS** [comment]
Note that this subsumes https://github.com/nhsconnect/gpconnect-demonstrator/issues/161 which only inhibited updating the cancellation reason in an amend
