### ISSUE TITLE
Reject the use of absolute references in Book, Cancel, Amend & Register Patient

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#200]
The GP Connect specification supports relative references only, e.g. 

`Patient/12345`
`Location/19C771AF-E1A4-4281-953E-2344F0AE424E`
etc

But NOT absolute references:

`https://test1.supplier.thirdparty.nhs.uk/A11111/STU3/1/GPConnect/Patient/12345`
`https://test1.supplier.thirdparty.nhs.uk/A11111/STU3/1/GPConnect/Location/19C771AF-E1A4-4281-953E-2344F0AE424E`
etc

Specification link:

https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#resource-references

Essentially the demonstrator should return an error from the demonstrator, suggested `422/INVALID_RESOURCE` (with details of the error in the `diagnostics` field)
if absolute references are sent in resources in the following interactions:

- Book Appointment
- Cancel Appointment
- Amend Appointment
- Register Patient

(i.e. the calls where resources are sent to the provider that may contain references)

This issue has been spotted in integration testing and would be good to catch earlier (i.e. in consumer testing against the demonstrator).

**Comment by SimonFarrowNHS** [comment]
Added Rusell as an assignee for consideration of a provider test for this as well.

**Comment by SimonFarrowNHS** [comment]
NB There do not appear to be any references in register patients so its not applicable for this issue
