### ISSUE TITLE
Other API calls - Bundle.fullURL is set to wrong value

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#201]
For the following interactions:

- Find Patient
- Find Practitioner
- Find Organization
- Retrieve a patient's appointments

the Bundle.fullUrl element has the wrong hostname in:

`"fullUrl": "https://data.developer.nhs.uk/gpconnect-demonstrator/v1/fhir/Patient/2"`

It should reflect the environment its deployed in:

So the internet 'orange box' would be:

`"fullUrl": "https://orange.testlab.nhs.uk/gpconnect-demonstrator/v1/fhir/Patient/2"`

The hostname (and possibly path if deployed to a different URL) would differ in other environments.

**Comment by SimonFarrowNHS** [comment]
This is already configurable item.
The default value is taken from the property serverBaseUrl in config/gpconnect-demonstrator-api.properties 
To configure a local override which will not be overwritten by git updates add an entry for serverBaseUrl to config/gpconnect-demonstrator-api.environment.properties 

Jonny and Russell added as assigness for action

**Comment by jonnyry** [comment]
all good, i will amend the orange box
