### ISSUE TITLE
JWT validation

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#209]
In order to ensure consumers are built in line with recently clarified JWT requirements at:

- Ticket: https://github.com/nhsconnect/gpconnect/issues/634 Spec: https://gpconnect-1-2-3.netlify.com/integration_cross_organisation_audit_and_provenance.html#jwt-payload
- Ticket: https://github.com/nhsconnect/gpconnect/issues/640 Spec: https://gpconnect-1-2-3.netlify.com/integration_cross_organisation_audit_and_provenance.html#exp-expiry-claim 

Suggest the following JWT validation should occur, and return an `OperationOutcome` with  information on the error in the `diagnostics` element where a failure occurs:

- Check the following claim names are *present* in the JWT:
  - `iss` (issuer)
  - `sub` (subject)
  - `aud` (audience)
  - `exp` (expiry)
  - `iat` (issued at)
  - `reason_for_request`
  - `requested_scope`
  - `requesting_device`
  - `requesting_organization`
  - `requesting_practitioner`

- Check `iat` and `exp` as per #222 

- Check that `reason_for_request` == `directcare`

- Check that `requested_scope` is in the list of valid values:
  - `patient/*.read`
  - `patient/*.write`
  - `organization/*.read`
  - `organization/*.write`

- Check `requesting_organization` is an `Organization` resource with:
  - a `name` element
  - an `identifier` element with
    - a `system` element containing `https://fhir.nhs.uk/Id/ods-organization-code`
    - a `value` element

- Check `requesting_practitioner` is a `Practitioner` resource with:
  - an `id` element
  - a `name` element, with
    - a `family` element
    - a `given` element
  - an `identifier` element, with
    - a `system` element containing `https://fhir.nhs.uk/Id/sds-user-id`
    - and a `value` element

**Comment by SimonFarrowNHS** [comment]
Extra requirements for validating requesting_device:
an identifier element should be present containing both system and value elements
version and model elements must also be populated.
