### ISSUE TITLE
Create new instance of demonstrator for 0.7.x

### ISSUE THREAD

**Issue by tim1ford** [nhsconnect/gpconnect-demonstrator#211]
0.7.2 has now been released and needs the corresponding demonstrator instance available (note this does not replace 0.5.x).

Both release notes from 0.7.0, 0.7.1 and 0.7.2 will need to be addressed:

https://developer.nhs.uk/apis/gpconnect-0-7-1/overview_release_notes_0_7_0.html
https://developer.nhs.uk/apis/gpconnect-0-7-1/overview_release_notes_0_7_1.html
https://developer.nhs.uk/apis/gpconnect-0-7-2/overview_release_notes_0_7_2.html

**Comment by jonnyry** [comment]
To be logged as individual tickets.

**Comment by SimonFarrowNHS** [comment]
Closed as per Jonny's comment above
