### ISSUE TITLE
Cosmetic changes required in demonstrator 0.5.0

### ISSUE THREAD

**Issue by tim1ford** [nhsconnect/gpconnect-demonstrator#212]
Date formats need updating to match the specification (dd-Mmm-yyyy)

Date sorting needs to be applied as per the spec.

**Comment by SimonFarrowNHS** [comment]
See https://developer.nhs.uk/apis/gpconnect-0-5-1/accessrecord.html for details

**Comment by SimonFarrowNHS** [comment]
This might initially be classified as cosmetic but it involves functional changes under the hood and requires significant effort to address.

**Comment by SimonFarrowNHS** [comment]
This positions the code for 0.7 and forms a good baseline for a new 0.7.1 feature branch
The data types in the database have been made more consistent and some invalid entries have been removed eg text appearing in numeric fields.
