### ISSUE TITLE
Dont populate Bundle.entry.fullUrl

### ISSUE THREAD

**Issue by SimonFarrowNHS** [nhsconnect/gpconnect-demonstrator#215]
After discussion with suppliers, it has been decided that Bundle.entry.fullUrl shall not be populated for all our capabilities

**Comment by SimonFarrowNHS** [comment]
See https://developer.nhs.uk/apis/gpconnect-1-2-3/overview_release_notes_1_2_3.html

**Comment by jonnyry** [comment]
Spec ticket link:
https://github.com/nhsconnect/gpconnect/issues/605
