### ISSUE TITLE
Organization resource in Search for free slots Bundle

### ISSUE THREAD

**Issue by SimonFarrowNHS** [nhsconnect/gpconnect-demonstrator#216]
In order progress the fix for the search for free slots _include parameter issue, consumers should now pass the _include:recurse=Location:managingOrganization parameter if they wish to return the Organization resource in the Search for free slots Bundle.

**Comment by SimonFarrowNHS** [comment]
This also affects the Capability Statement. 
Currently this parameter is allowed but ignored as part of backward compatibility.

**Comment by jonnyry** [comment]
Hi @SimonFarrowNHS, the provider should still continue to "ignore" the parameter - i.e. still send the Organization resource regardless.  The main change in this spec is that the consumer can now send the parameter.

Also the capability statement has been updated to add the parameter to it.

**Comment by jonnyry** [comment]
Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#organization-resource-in-search-for-free-slots-bundle
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/645
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/216
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/225

**Comment by SimonFarrowNHS** [comment]
Glad you mentioned that it should still be ignored. That's half an hour of last Friday wasted then :-) (backs out change)

**Comment by jonnyry** [comment]
Ah sorry about that!

**Comment by SimonFarrowNHS** [comment]
Closed since this does not impact the Demonstrator
