### ISSUE TITLE
Date/time formats in Appointments

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#218]
- The following elements are in UK local time in the format `yyyy-mm-ddThh:mm:ss+hh:mm` using timezone offset +00:00 for UTC and +01:00 for BST:

  - Slot.start
  - Slot.end
  - Schedule.planningHorizon.start
  - Schedule.planningHorizon.end
  - Appointment.start
  - Appointment.end
  - Appointment.created

  (it looks like the Demonstrator is currently sending +00:00 for dates in BST)
 
- Search for free slots start and end parameters can either be:
  - dates in the format `yyyy-mm-dd`
  - dateTimes in the format `yyyy-mm-ddThh:mm:ss+hh:mm` in UK local time with the timezone offset +00:00 for UTC and +01:00 for BST

- Suggest the following Search for free slots validation to prompt consumers to fix their systems (rejected with an error message):

  - Sending a search for free slots start or end parameter with an incorrect timezone, e.g. -02:00
  - Sending the wrong timezone for the time of year, e.g. +00:00 when it's actually BST
  - Sending no timezone
  - Sending a 'Z' in place of +00:00

  (Some of the above have already been seen in current systems)

- Suggest the following validation on Book, Amend, Cancel
  - the appointment start and end elements match exactly the slot start and end elements, including the timezone offset

- Retrieve a Patients Appointments search filters only supports dates.  dateTimes are not supported.
  - Suggest throwing an error if dateTimes are sent

---

Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#clarify-date--time-component-use-in-appointments
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/646
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/218
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/223

**Comment by SimonFarrowNHS** [comment]
Appointment search validation already behaves as requested
