### ISSUE TITLE
Amending a cancelled appointment is no longer supported

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#219]
(This may have already been implemented)

If a cancelled appointment is amended, return a 422 error with error code INVALID_RESOURCE.

---
Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#amending-a-cancelled-appointment-is-no-longer-supported
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/601
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/219
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/226

**Comment by SimonFarrowNHS** [comment]
Am I missing something here? I thought this was already implemented at 1.2.2 see #199

**Comment by jonnyry** [comment]
No I've created a duplicate, let's close this one.
