### ISSUE TITLE
Default date range if only a start or end date parameter passed in getCareRecord

### ISSUE THREAD

**Issue by tim1ford** [nhsconnect/gpconnect-demonstrator#224]
The scenario where only a start or an end date need to be considered and the GP Connect program needs to update the specification to cater for the possibility of someone only sending a start date or an end date

**Comment by SimonFarrowNHS** [comment]
This also applies to 0.5.2
See https://developer.nhs.uk/apis/gpconnect-0-5-2/accessrecord_development_html_layout_guide.html
