### ISSUE TITLE
Default Date Range Banner Message Wording

### ISSUE THREAD

**Issue by tim1ford** [nhsconnect/gpconnect-demonstrator#225]
Requirements added to fully describe the expected date banner wording.

More information can be found [here](https://github.com/nhsconnect/gpconnect/issues/162) and [here](https://developer.nhs.uk/apis/gpconnect-0-7-0/accessrecord_development_html_layout_guide.html#default-date-ranges)

**Comment by SimonFarrowNHS** [comment]
Also applies to 0.5.2
