### ISSUE TITLE
Updates for 1.1.0 of the spec

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#23]
1. Add the example of new searchFilter parameter to the demonstrator as outlined here:

Enhanced slot filtering - 
https://developer.nhs.uk/apis/gpconnect-1-1-0/appointments_use_case_search_for_free_slots.html

We should have examples for two example Org ODS codes and the two types of org type from the value set. It might be worth adding the ODS codes to the README.md so it is recorded somewhere.

2. On the returned schedule we need to populate the new practitioner role and delivery channel extensions:

https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Schedule-1

We probably want to setup two or three schedule to be returned with different combinations of practitioner role and delivery channel.

**Comment by lucywilcock** [comment]
Step 1 (Enhanced slot filtering) has been completed pending review. The front end now sends down the additional searchFilter parameters. The back end then searches for slots that are available to the booking organisation or organisation type. Only slots that are available will appear in the appointment search. Booking appointments should work as before.

**Comment by tgmay** [comment]
Step 2 (extensions) has been completed pending review (feature branch app-schedule-extensions). The practitioner role and delivery channel for each schedule are stored in the database and returned as extensions on the schedule bundle entry by the back end. The front end displays the role and delivery on both the appointment slots modal and the appointment create modal.

**Comment by lucywilcock** [comment]
Step 1 has been merged with develop and is Done.

**Comment by tgmay** [comment]
This has been merged back into develop and is done.
