### ISSUE TITLE
Check List.warningCode scenarios implemented in the demonstrator

### ISSUE THREAD

**Issue by mstephens-xsl** [nhsconnect/gpconnect-demonstrator#237]
One of the changes in 1.2.3 is a change to the text returned in List.note when data is in transit. [#650](https://github.com/nhsconnect/gpconnect/issues/650).

It would be good to check whether the different scenarios for warningCode are included in the test data in the demonstrator. The list is available at:

[List.warningCode values](https://developer.nhs.uk/apis/gpconnect-1-2-3/accessrecord_structured_development_list.html#warning-codes)

This is important as the demonstrator forms a significant part of a consumers testing when implementing the GP Connect APIs. Thought will need to be given by the GP Connect team on how this should be implemented and prioritised.

**Comment by SimonFarrowNHS** [comment]
#263 and #266 seem to cover this now.
