### ISSUE TITLE
Update links on banner to the new spec deployments

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#24]
The banner links to the wrong urls for the spec. They need to be updated as follows:

**DSTU2 Spec:** https://developer.nhs.uk/apis/gpconnect-0-5-0/

**STU3 Spec:** https://developer.nhs.uk/apis/gpconnect-1-0-0/

**Comment by lucywilcock** [comment]
Have completed and deployed to develop.
