### ISSUE TITLE
Book Appointment - booking organisation telecom

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#241]
(this may already been implemented...)

When booking an appointment, ensure at least one booking organisation telecom element is sent through.

This was picked up in integration testing and caused issues with a provider system that expected a telecom to be there, when one wasn't being sent by the consumer.

**Comment by SimonFarrowNHS** [comment]
This is already implemented.  The demonstrator requires at least one telecom to be present at least one of which must be of type phone
