### ISSUE TITLE
Remove reference.display where populated

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#243]
The `reference.display` element is not consistently populated by provider systems or the demonstrator, and in order that consumers don't think that it is consistently populated and rely upon it, it would be good to remove this element where populated.

For example the following is from the Find Patient call:

```
         "generalPractitioner": [
          {
            "reference": "Practitioner/1",
            "display": "Miss Nichole Gilbert"
          }
        ],
        "managingOrganization": {
          "reference": "Organization/7"
        }
```

(so the action would be to remove the display element from the generalPractitioner element)

This applies to all resources returned from the 1.x Demonstrator.

**Comment by SimonFarrowNHS** [comment]
As far as I can tell this is the only place where a reference resource has a display value set. It has now been removed
