### ISSUE TITLE
Update metadata endpoint to match spec changes

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#25]
The spec was updated with requirements to follow the example as a template and to include the spec version in the Conformance/CapabilityStatemnt. We need to update the metadata endpoint to return the additional information and try to match the spec. It is currenty generated so we will either need to overwrite stuff or change it to a hard coded response.

https://developer.nhs.uk/apis/gpconnect-0-5-0/foundations_use_case_get_the_fhir_conformance_profile.html

&

https://developer.nhs.uk/apis/gpconnect-1-0-0/foundations_use_case_get_the_fhir_capability_statement.html

**Comment by lucywilcock** [comment]
I have added name, version, description, copyright and the HAPI FHIR release date to the conformance statement for V1.0.0. This can be found in branch update-metadata.

I have overridden the existing ServerCapabilityStatementProvider and added in the above fields to the existing capability statement. All other fields exist as they did before.

The FHIRFeature tests in the test suite (which check the metadata) all still pass.

**Comment by james-answer** [comment]
The key elements seem to be there and the other elements should be auto generated still so this looks good to be merged back in.

**Comment by lucywilcock** [comment]
Copied changes to 0.5.0 (slight differences due to FHIR DSTU2 but all additions to metadata are the same).

Merged in with develop and release/0.5.0 respectively.
