### ISSUE TITLE
Table column name amendment

### ISSUE THREAD

**Issue by Sado1234** [nhsconnect/gpconnect-demonstrator#253]
This was identified by EMIS on the back of assurance testing 0.5.2 version. 

- Scheduled End Date needs to be changed to Schedule End

Spec https://developer.nhs.uk/apis/gpconnect-0-5-2/accessrecord_view_medications.html#table-columns

For Current medication issues > Table columns > Name:
**Expected:**
Start Date,Medication Item,Type,Scheduled End,Days Duration,Details
**Actual:**  
Start Date,Medication Item,Type,Scheduled End Date,Days Duration,Details

relates to Provider suite ticket (https://github.com/nhsconnect/gpconnect-provider-testing/issues/268)

**Comment by SimonFarrowNHS** [comment]
NB for the avoidance of doubt this change does NOT apply to 0.7.2 where the spec states that the column name is Scheduled End Date
