### ISSUE TITLE
Add in Meta profile in payload request body

### ISSUE THREAD

**Issue by Sado1234** [nhsconnect/gpconnect-demonstrator#254]
EMIS have increased their validation checks on **Register patient** request payload and Jonny Rylands has confirmed that the meta.profile should be included in the payload. 

GPConnect-RegisterPatient-Operation-1 profile is present :

**parameter.resource.meta.profile = "https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1"**

**Current request body**
`
<fhirRequestParameters> {
    "resourceType":"Parameters",
    "parameter":[ {
        "name":"registerPatient",
        "resource": {
            "resourceType":"Patient",
            "identifier":[ {
                "extension":[ {
                    "url":"https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-NHSNumberVerificationStatus-1",
                    "valueCodeableConcept": {
                        "coding":[ {
                            "system": "https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-NHSNumberVerificationStatus-1", "code": "01"
..... 
`

**Expected as per Spec (https://developer.nhs.uk/apis/gpconnect-1-2-3/foundations_use_case_register_a_patient.html#payload-request-body)**
`{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "registerPatient",
      "resource": {
        "resourceType": "Patient",
        "meta": {
          "profile": [
            "https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1"
          ]
        },......
`

** No validation - Error code no longer required:**

**There are meta profiles for Appointments _and in upcoming Advanced Structure_**
Book an Appointment
Amend an Appointment
Cancel an Appointment

"resourceType": "Appointment",
  "meta": {
    "profile": [
      "https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1"
    ]

Relates to provider ticket (https://github.com/nhsconnect/gpconnect-provider-testing/issues/269)

**Comment by Sado1234** [comment]
Hi @SimonFarrowNHS after further discussions with @jonnyry he has requested the meta.profile be present in the request payload but not to do any validation so perhaps you can close off this ticket with no dev work required?

**Comment by SimonFarrowNHS** [comment]
Thanks Sara. Closing this now since the morning call has agreed to this
