### ISSUE TITLE
Implement a check in the Demonstrator for parameter values sent in a Consumer request

### ISSUE THREAD

**Issue by privchiadzwa** [nhsconnect/gpconnect-demonstrator#259]
Implement a check in the Demonstrator for searchFilter parameter values sent in a Search For Slots request by a Consumer System.

Demonstrator should return an error code 400 where invalid parameter values are sent in a Consumer request
Where Parameter name IS searchFilter THEN Parameter value - system element MUST BE
https://fhir.nhs.uk/Id/ods-organization-code OR https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1

Where Parameter name IS searchFilter AND Parameter value - system element IS https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1 THEN Parameter value - code element MUST BE 
urgent-care OR GP Practice

**Comment by SimonFarrowNHS** [comment]
On hold pending review against text in spec re search filters:
Where search filters are sent by consumers which are not explicitly supported in this specification (for example, urgent care use a disposition code value set), providers who do not understand the additional parameters SHALL ignore them and SHALL NOT return an error.

**Comment by SimonFarrowNHS** [comment]
See https://nhsconnect.github.io/gpconnect/appointments_use_case_search_for_free_slots.html 
Jonny R has confirmed via email that the current behaviour is correct. Change not implemented.
