### ISSUE TITLE
0.5.0 - Incorrect error when request is invalid

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#26]
If you send an Access Record HTML request to the 0.5.0 demonstrator where the system for the section is incorrect the response says "Patient not found" which is incorrect and missleading for consumers testing against it.

The code needs updating to send back a correct error code when the system for the section is wrong. It would be worth checking that the other parameters when sent incorrectly return an accurate error code and description.

**Comment by lucywilcock** [comment]
This error should now send back the message 'Invalid system'. The change is in the branch named 'incorrect-section-error'.

Similar errors were also returned if the system or section name was null, if the section name was incorrect, if dates were invalid and an unrecognised organisation referenced the practitioner. These have also all been changed.

Additionally, an nhs number validation error in the FhirRequestAuthenticator returned 'Dates invalid' this has also been changed to show a validation error.

All tests still run (and pass) as expected.
