### ISSUE TITLE
0.5.0 - Remove provider names from NHS Number buttons on search window

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#27]
On the 0.5.0 demonstrator the buttons for example patients still have the provider names which is a hang over from when the demonstrator returned example data supplied by the providers. We need to removed the provider names from the example NHS Number buttons.

**Comment by lucywilcock** [comment]
This has been completed in branch remove-providers-050. The example patient buttons now only show the NHS numbers as with the 1.0.0 demonstrator.
