### ISSUE TITLE
https enabled without mutual auth

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#28]
Currently if the demonstrator is running on https it requires mutual authentication with a cert from the consumer. We have been asked if it can run on https without mutual auth so that the demonstrator can be linked through from the swagger definition Jonny is creating which runs on https.

The best solution would probably be to check the client auth parameter to see if it is false, if so the client certificate checks can be skipped, allowing the demonstrator to run over https without client authentication.

**Comment by lucywilcock** [comment]
This has been completed in branch https-without-mutual-auth. If the request is secure then it will also look for a clientAuth parameter. If this is set to false then it will skip the mutual authentication. If this parameter is left out or set to anything other than 'false' then mutual authentication will still occur.
