### ISSUE TITLE
INVALID_PARAMETER response when using the demonstrator UI

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#322]
When I try and retrieve a patient record using the 0.7.2 UI I get the following error:

Status: 422
Error Code: INVALID_PARAMETER

**Comment by SimonFarrowNHS** [comment]
This is as a result of #302.

The gui will need to be modified to send a date range.

**Comment by SimonFarrowNHS** [comment]
Gui modified to not pass null data parameters for summary, allergies and immunizations
