### ISSUE TITLE
Structured Record - Medications: Front End

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#33]
A new page will need to be created for the [Structured Record: Medications](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medications_introduction.html) section of the demonstrator. This will need the html and service and controller writing. 

The page should send the getstructuredrecord (/Patient/$gpc.getstructuredrecord-1) request for the medications section and display the data that is returned. 

The backend will be developed separately.

**Comment by saurabhkjain** [comment]
Created a a frontend for medications.
