### ISSUE TITLE
Structured Record - Medications: Database

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#34]
Medications will be implemented in the backend for the new Access Record - Structured.

Medication entities already exist as leftovers from the HTML Record capability in V0.5.0. These should be reviewed and either deleted and recreated or altered to fit the new requirements.

Also review the data that is added into these entities for display in the front end and alter as required.

**Comment by tgmay** [comment]
Medication, MedicationRequest and MedicationStatement entities have been created with associated SQL scripts and sample data for a subset of the patients. 

Entities and resource providers that exist as leftovers from the HTML Record capability in V0.0.5 have been deleted.

Branch: feature/structured-medications

**Comment by saurabhkjain** [comment]
This has been fixed.

**Comment by saurabhkjain** [comment]
pushed to develop.
