### ISSUE TITLE
Structured Record - Medications: Bundle

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#35]
The [Medications](http://gpconnect-structured.netlify.com/accessrecord_structured_development_medications_introduction.html) section of Access Structured Record will be implemented in GpConnect 1.2.0.

The data needs to be returned as a [searchSet bundle](http://gpconnect-structured.netlify.com/accessrecord_structured_development_retrieve_patient_record.html#payload-response-body) and should include patient, practitioner and organiser data.

The bundle needs to be built up when the call is sent. The call itself will be handled in issue 31. This task is to create the bundle with the data from the patient record.

**Comment by tgmay** [comment]
Still to be completed:
- Error handling for missing information, e.g. statement without reference to medication request
- Validation on date parameters - only accept the format "yyyy-MM-dd"
- Review data in SQL scripts, there may be a need to add more for different scenarios. Note that ID's will need to be explicit

There may be changes to be made on entities and bundle structure following the review of discrepancies in this [issue](https://github.com/nhsconnect/gpconnect/issues/381#issuecomment-376479039).

All work completed so far is on the feature/structured-medications branch.

**Comment by saurabhkjain** [comment]
pushed to develop .
