### ISSUE TITLE
consultations  - participant element updated default and also has wrong address

### ISSUE THREAD

**Issue by PeterGresty** [nhsconnect/gpconnect-demonstrator#351]
A 1.5.0 spec change has been made to consultations/encounters  participant element to change default code value from AUTH to REC as per this updated spec page... https://gpc-structured-1-5-0.netlify.app/accessrecord_structured_development_encounter.html#period 

Also the system address is wrong in that element as well.. currently returns >                     "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType", but should return >>>"https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-ParticipantType-1"

**Comment by SimonFarrowNHS** [comment]
Amended consultations_resp.xml accordingly

**Comment by SimonFarrowNHS** [comment]
@Peter Does the display element need to change from author to something like recorder or does it stay as it is?

**Comment by SimonFarrowNHS** [comment]
Also display element author become recorder

And after discussions with Martin Hillyard and reference to spec

Display test "Primary Performer" becomes "primary performer"
