### ISSUE TITLE
public  facing demonstrator shows the appointments booked multiple times

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#36]
On the public facing demonstrator for 1.0.0 when you create an appointment it shows multiple times in the list for booked appointments. This is probably a database configuration error on the example federated practices.

**Comment by lucywilcock** [comment]
This is working correctly.

**Comment by lucywilcock** [comment]
I can no longer replicate this bug.

Closing until it is seen again.
