### ISSUE TITLE
Update location test data

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#43]
The location should contain a name and address, this should be reflected on the UI for the demonstrator to make it clear what information will be returned from the provider.

**Comment by lucywilcock** [comment]
There is now an address entity in the database and a foreign key referencing an address from a location. The location already had a name field.

These are both now displayed in the demonstrator. This can be seen in the final dialog when booking an appointment and when viewing the appointment details. They are currently displayed in a single line for simplicity's sake (under the label Location) although they can be separated out if required.

The code can be found in feature branch location-add-address.

All tests run as expected.

**Comment by lucywilcock** [comment]
Reminder: if merging with develop then test data for extra practices on public facing demonstration must be updated manually. SQL files are: create_tables, populate_appointment_data

**Comment by lucywilcock** [comment]
This has been merged into develop and master and the 1.1.0 tag has been moved.

The sql has been updated manually for the public facing demonstrator and all three are displaying the Location address.
