### ISSUE TITLE
Bundle full URLs are at an unresolvable address

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#45]
Example from Patient call returned from https://orange.testlab.nhs.uk/v1/fhir/Patient:

````
"link": [
    {
      "relation": "self",
      "url": "http://127.0.0.1:9091/fhir/Patient?identifier=https%3A%2F%2Ffhir.nhs.uk%2FId%2Fnhs-number%7C9476719958"
    }
]
````

**Comment by james-answer** [comment]
I have made it possible to configure the base url through the application.properties file. The other option to add proxy headers in the NGINX so that the application can use the server url seemed like a more complicated solution.

property: serverBaseUrl=base_url
