### ISSUE TITLE
ReadMe contains invalid run commands

### ISSUE THREAD

**Issue by Chrisjobling** [nhsconnect/gpconnect-demonstrator#50]
The readme file specifies three ways of running the demonstrator via command line. Whilst setting up the project, developers were confused as two of the commands are now invalid given the demonstrator requires two ports to be specified. The commands should be removed from the read me.

The valid command is  : **java -jar gpconnect-demonstrator-api\target\gpconnect-demonstrator-api.war --server.port=19192 --server.port.http=19191 --config.path=config\ --server.ssl.key-store=config\server.jks --server.ssl.key-store-password=password --server.ssl.trust-store=config\server.jks --server.ssl.trust-store-password=password --server.ssl.client-auth=want**

**Comment by james-answer** [comment]
Done on Master and Develop
