### ISSUE TITLE
CodeableConcept system using valueset url rather than codesystem url

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#53]
A github issue has been raised for the GP Connect test suite to look through all the CodeableConcepts and check the System validation to make sure it uses the "CodeSystem" rather than the "ValueSet" for the system element:

https://github.com/nhsconnect/gpconnect-provider-testing/issues/34

This is because the test suite is sometimes validating resources have the valueset as the system rather than the codesystem.

We need to check that the resources returned and validation within the demonstrator use the correct "CodeSystem" from the valueset for the CodeableConcept rather than the "ValueSet" URL for the system.

**Comment by lucywilcock** [comment]
This has been fixed. All coding system now point to the code set URL. All value sets still point to the value set URL.
