### ISSUE TITLE
Test data warning message

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#58]
Please could we add a warning message to the front page of the demonstrator (both versions) to say:

"This is a test server. Do not store any information here that contains personal health information or any other confidential information. This server will be regularly purged and reloaded with fixed test data."

**Comment by james-answer** [comment]
This should apply to both the 0.5.x and 1.x.x demonstrator.

**Comment by lucywilcock** [comment]
The warning message has been added to both demonstrators. It has also been added to the 1.2-beta branch and the develop branches.
