### ISSUE TITLE
Appointment Reason

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#60]
In the 1.1.1 specificaiton it was made more strict that the Appointment.Reason should not be populated. We need to make sure the demonstrator backend is strict and does not allow the element, making sure it returns the correct error if a reson is included in the appointment.

This may have already been done we just need to check that it validates appointment booking correctly.

**Comment by saurabhkjain** [comment]
Appointment.Reason will not be included in the response the AppointmentDetail model in the demonstrator does not have a 'Reason' field and hence it is not used to map it to an appointment.

**Comment by lucywilcock** [comment]
We need the demonstrator to error if the consumer sends a reason in the request. Can we double check that the demonstrator does this please.

**Comment by saurabhkjain** [comment]
Added a check to the demonstrator to check if the consumer send the reason in the request and throws a 422 error. 
This has been pushed to master branch

**Comment by lucywilcock** [comment]
This all looks correct.  Closing.
