### ISSUE TITLE
Register Patient Telecom and Address

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#63]
The 1.1.1 specification says that the consumer can only send temp telecom and temp address details. If the consumer send them the provider should store the details.

If the register patient request contains temp details then they should be returned in the patient response.

**Comment by saurabhkjain** [comment]
Pushed the code to master.

**Comment by lucywilcock** [comment]
Reviewed, all looks okay to me. Related tests now pass.
