### ISSUE TITLE
1.2.0 - Practitioner Role

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#64]
It has been decided that the bundle returned in a structured record request should contain a practitioner role resource. This should be added to both the medications and allergies requests.

The [bundle](http://gpconnect.netlify.com/accessrecord_structured_development_retrieve_patient_record.html#bundle-population-illustrated) should also always contain a patient, practitioner and organisation resource. Please check that these are already included and add them in if necessary.

**Comment by damian-answ** [comment]
add practitioner role, update recorder id in database (allergy intolerance)

**Comment by lucywilcock** [comment]
After running the structured record tests I can see that the practitioner role resource is not being added to the bundle on patient's 5, 6, 7 or 8. This is causing the tests to fail. The resource is being added to the other patients.

**Comment by damian-answ** [comment]
there was missing role_id in one of practitioner rows, now should works

**Comment by lucywilcock** [comment]
This all looks good.

Please push to develop and close the issue when done.
