### ISSUE TITLE
1.2.0 - Response

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#67]
Below are several new criteria for the response bundle. Make sure that the demonstrator supplies the correct details.

-  the NHS number in the response Patient resource matches that sent in the body of the request
- the response Organization matches the patient’s registered GP practice, referenced from Patient.generalPractitioner
- if the organization serving the request is different from registered GP practice, then the organisation serving the request must also be included in the return bundle. This will be referenced from Patient.managingOrganization
- the response practitioner matches the patient’s usual GP, referenced from Patient.generalPractitioner
- the practitionerRole matches the patient's usual GP’s role

**Comment by saurabhkjain** [comment]
Added a check to verify the NHS number in the response matches that send in the body of the request. 

This has been pushed to 1.2.0-response branch.

**Comment by saurabhkjain** [comment]
Pushed to develop.
