### ISSUE TITLE
1.2.0 - Include Parameters Mandatory

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#68]
For the medications and allergies request the 'include' part parameters (i.e. includeResolvedAllergies and includePrescriptionIssues) are now mandatory if the parent parameter is present (i.e. includePrescriptionIssues is not necessary if only allergies are requested). If they are not present in the request we should error as in other places.

The medication date parameters are still optional.

**Comment by lucywilcock** [comment]
We should also error if the wrong part parameters are included in the request. For example, in includeResolvedAllergies is inlcuded in a request for medication data only or if includePrescriptionIssues is included in an allergy-only request.

**Comment by damian-answ** [comment]
added throw exception when request doesn't contain include params 
branch: feature/IncludeParametersMandatory-68

**Comment by lucywilcock** [comment]
This looks good. Please merge back into develop.
