### ISSUE TITLE
1.2.0 - Resolved Allergies List

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#69]
Resolved allergies resources must now be returned IN the resolved allergies list, not just referenced from it. See [this](http://gpconnect.netlify.com/accessrecord_structured_development_retrieve_patient_record.html#bundle-population-illustrated) diagram.

Active allergies should still be returned individually and only referenced from entries in the list.

**Comment by damian-answ** [comment]
add resolved allergies as cointained and set correct reference to that (with '#' before id)
changes on branch feature/ResolvedAllergiesList-69

**Comment by lucywilcock** [comment]
The line 'buildingListResource.setId(allergyIntolerance.getId());' is duplicated in both parts of the if statement in the method StructuredAllergyIntoleranceBuilder.listResourceBuilder. Please move it to outside of the if so it is only used once.

Otherwise this looks good. When this above is done please merge into develop.

**Comment by lucywilcock** [comment]
The resolved allergies are still being returned as resources in the bundle. They should only be returned as contained resources inside the Resolved Allergies list.

**Comment by damian-answ** [comment]
Ok, updated.

**Comment by lucywilcock** [comment]
Please ensure that the resolved allergies are still visible on the front end of the demonstrator - they no longer seem to be shown.

**Comment by lucywilcock** [comment]
The above was already done, I just hadn't updated the front end. All is working fine.
