### ISSUE TITLE
1.2.0 - No medications

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#71]
Ensure that the demonstrator correctly returns the bundle for a patient with no medications. Ensure the list is correct according to the latest [spec](http://gpconnect.netlify.com/accessrecord_structured_development_medication_resource_relationships.html#using-the-list-resource-for-medication-queries).

**Comment by lucywilcock** [comment]
The variable changed is also used for allergies. I'm pretty sure allergies does need to be 'Information not available': http://gpconnect.netlify.com/accessrecord_structured_development_allergies_guidance.html#negation---handling-no-known-allergies.

**Comment by saurabhkjain** [comment]
Added NO_CONTENT_RECORDED constant for allergies. 
Updated the list.note value to be "Information not available"

**Comment by lucywilcock** [comment]
Looks good.
