### ISSUE TITLE
1.2.0 - Medications prescribed elsewhere

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#72]
Add a patient who has medications prescribed elsewhere and ensure the bundle is returned correctly as per the latest [spec](http://gpconnect.netlify.com/accessrecord_structured_development_medication_resource_relationships.html#unissued-medications-and-medication-prescribed-elsewhere).

**Comment by damian-answ** [comment]
- add PrescribingAgency field as a extension, also in database and model classes
- add request with intent:plan and correlate with statement 
- test works in locally

changes on branch: MedicationPrescribedElsewhere-72

**Comment by lucywilcock** [comment]
A couple of things.

In MedicationStatementResourceProvider:
- Line 70 - please move the URL into the SystemURL class and reference it from there. That way if we need to use it again or if it is ever changed the modification is in a single place.
- Line 71 - this extension needs a CodeableConcept. The spec still says that the valueset is to be confirmed but we should have the correct type in place. For now you could add a system of TBD and a code/display equal to the prescribingAgency string (or something else you feel is appropriate).

**Comment by damian-answ** [comment]
updated and merged to develop
