### ISSUE TITLE
1.2.0 - Registration Period

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#73]
When running one of the allergies tests it was noticed that the registrationPeriod extension does not return a value. This is part of the registration details extension (url:  https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-RegistrationDetails-1)

Please ensure that any time we return the registration details extension we also return, at least, a start date for the registration period. This should be the same for all structured record requests.

**Comment by saurabhkjain** [comment]
Hi, 

I have run through every allergies test in the test suite and am unable to locate the test where "the registrationPeriod extension does not return a value". 

Could you please confirm if this is still an issue. 
I ran the test from the develop branch.

**Comment by lucywilcock** [comment]
Any patient returned with a registration period should have the value populated. 

Eg (from register patient):
 "extension":[{"url":"https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-RegistrationDetails-1","extension":[{"url":"registrationPeriod","valuePeriod":{"start":"1962-07-13T00:00:00+01:00"}}]}]

As long as this is true then the issue has been fixed and the issue can be closed.

**Comment by saurabhkjain** [comment]
Currently all valid tests are returning the above. 

Closing the issue.
