### ISSUE TITLE
1.2.0 - Allergies FHIR Resources

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#74]
The allergies FHIR resources page has been updated with changes to the following fields:
- encounter
- allergyEnd (inc endDate and endReason)
- identifier
- asserter
- recorder
- lastOccurence

Please ensure the demonstrator is up to date with the latest rules with regards to these fields in particular.

**Comment by lucywilcock** [comment]
Note: the endReason url has changed to reasonEnded: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-AllergyIntoleranceEnd-1

**Comment by damian-answ** [comment]
- add encounter extension (database column and data - populate patient 2 has encounter 11)
- update allergyEnd extension
Everything else looks fine for me. Changes on branch AllergiesFHIRResources-74

**Comment by lucywilcock** [comment]
- Please add the encounter URL as a FHIR StructureDefinition Extension in SystemUrl. 
- The encounter reference should be in the form 'Encounter/*id*' not just the id (and please remove the commented out code)

When this has been done please merge with develop and close the ticket. Thank you.

**Comment by damian-answ** [comment]
updated, closed
