### ISSUE TITLE
1.2.0 - Medications FHIR Resources

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#75]
The medications request FHIR resources pages has been updated. There have been changes to the following fields:
- identifier
- basedOn
- groupIdentifier
- dosageInstruction

Please ensure the demonstrator is up to date with regards to these fields in particular.

**Comment by lucywilcock** [comment]
Please also check:
- statusReason (with associated date and reason fields)

**Comment by saurabhkjain** [comment]
Added an identifier to the medication bundle. 

All else looks fine.
