### ISSUE TITLE
1.2.0 - List FHIR Resources

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#76]
The List FHIR resources page has had changes to the following fields:
- title
- warningCode
- clinicalSetting

Please ensure the demonstrator is up to date with regards to these fields in particular.

**Comment by lucywilcock** [comment]
List titles have now been clarified:
- Medications and medical devices (for medication list)
- Allergies and adverse reactions (for active allergies)
- Resolved allergies (for resolved allergies, temporary, awaiting confirmation from SNOMED but use this for now)

**Comment by saurabhkjain** [comment]
Added code and acceptance tests to handle warningCode and clinicalSetting.

**Comment by lucywilcock** [comment]
Clinical Setting and Title changes look good. Thank you.

A few changes for warning codes:
- This was my misunderstanding (apologies): I originally advised that if there were warning codes in the patient record then no data should be returned, this was wrong. The data that is there should still be brought back regardless of the existence of a warning code.
- If there is a warning code in a patient record then this should be displayed in the front end of the demonstrator.
- Please make sure the warning code used matches those in the [spec](http://gpconnect.netlify.com/accessrecord_structured_development_list.html#warning-codes). I'd maybe use the 'Confidential items' code as this seems the best defined and can be applied to meds or allergies resources separately.
- Please make sure any URLs are added to SystemURL and access them from there.
- Please make sure to update the pre-requisite file to note which patients should have warning codes.
- Currently several tests are failing for patient 2 in the test suite. Please check these - I suspect they will pass again when patient data is brought back regardless of the existence of the warnings code.
- For the warning code test, please add a check to ensure that, for this patient, the warning code exists in the expected list(s).

**Comment by saurabhkjain** [comment]
updated the code as per above changes.
