### ISSUE TITLE
1.2.0 - Duplicate note on allergy list

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#77]
The tests Retrieve the allergy structured record section excluding resolved allergies for a patient without any allergies and Retrieve the allergy structured record section including resolved allergies for a patient without any allergies are failing because the allergy list is being returned with two identical notes:
"note":[{"text":"Information not available."},{"text":"Information not available"}],"

**Comment by damian-answ** [comment]
remove duplicate and pushed directly to the develop branch
