### ISSUE TITLE
1.2.0 - Logical Identifier must be persisted

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-demonstrator#78]
The id field of the allergyIntolerance, medicationStatement and medicationRequest resources now has a new requirement stating that it **must** be a GUID and **must** be persisted. Please check that this is the case for the demonstrator.

See the spec's relevant FHIR resources page for the exact wording.

**Comment by damian-answ** [comment]
add guid column, set guid as id in allergyintollerance, medication request and med. statement

changes on branch: feature/logicalIdentifierMustBePersisted-78

**Comment by lucywilcock** [comment]
This looks fine with me. Please merge with develop but keep the ticket open until issue 63 in the test suite has been completed.

**Comment by damian-answ** [comment]
updated, now medications tests should work

**Comment by lucywilcock** [comment]
Medication tests are now passing. Please merge with develop but keep the ticket open until issue 63 in the test suite has been completed.

**Comment by damian-answ** [comment]
updated and merged to develop

**Comment by lucywilcock** [comment]
Tests are complete and passing. Closing.
