### ISSUE TITLE
Dockerize demonstrator

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#81]
One of the requiremnts is to deploy the demonstrator to the developer network using docker. Therefore we need to dockerize the demonstrator, making sure the script and config is setup correctly.

**Comment by damian-answ** [comment]
Created dockerfile in branch 1.1.1-docker.
To build image copy config folder into target/ and type:
"docker build -f Dockerfile -t image_name ."
There are two env variables that indicate database:
DATABASE_ADDRESS and DATABASE_PORT
so image could work with external database and db in another container.

**Comment by damian-answ** [comment]
readme updated
