### ISSUE TITLE
Duplicate Schedule resources are returning in response to Search for free slots call

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#90]
When making a call to Search for free slots, e.g.

https://orange.testlab.nhs.uk/v1/fhir/Slot?start=ge2018-09-25&end=le2018-09-27&status=free&_include=Slot%3Aschedule&_include%3Arecurse=Schedule%3Aactor%3APractitioner&_include%3Arecurse=Schedule%3Aactor%3ALocation&searchFilter=https%3A%2F%2Ffhir.nhs.uk%2FSTU3%2FCodeSystem%2FGPConnect-OrganisationType-1%7Cgp-practice

Multiple Schedule resources are returned with the same logical identifier.

It appears that there is one Schedule resource per Slot, even if the Slot is referring to a Schedule that has already been referenced.

**Comment by SimonFarrowNHS** [comment]
Code amended to only add unique schedules and practitioners once. That has significantly de-bloated the search for free slots response.

**Comment by jonnyry** [comment]
de-bloated :-)
