### ISSUE TITLE
Uplift capability statement to 1.2.1

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#91]
1. Change the version element in the CapabilityStatement so it matches current GP Connect spec version (i.e. = 1.2.1).

2. Check the contents of the capability statement are in line with the current capability statement - see [Get the FHIR capability statement](https://nhsconnect.github.io/gpconnect/foundations_use_case_get_the_fhir_capability_statement.html#payload-response-body)  I think there were a few elements missing last I cross checked it.

3. Change the version number on the demonstrator website i.e. https://orange.testlab.nhs.uk/v1/#/ 

---
In line with 1.2.1 release note  https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#foundations

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
