### ISSUE TITLE
Remove lastUpdated from all resources

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#92]
In line with changes at:  https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#core-specification

1. Remove meta.lastUpdated from all resources.  This is no longer a mandatory element (see text below).  So that consumers do not attempt to rely on it, it is best that we remove it altogether from the demonstrator.

Spec change:

"Providers MAY populate meta.lastUpdated (unless stated otherwise in a profile’s population guidance) if they hold an accurate date/time associated with the data items making up the profile. Consumers MUST NOT rely on this value being populated."

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
