### ISSUE TITLE
Delivery channel - Schedule and Slot resources

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#93]
1.  Remove Extension-GPConnect-DeliveryChannel-1 from GPConnect-Schedule-1 profile.

2. Add Extension-GPConnect-DeliveryChannel-2 to GPConnect-Slot-1 profile.
Note this extension is different from the one removed from Schedule as it uses a 'code' instead of a 'CodeableConcept'.  See payload example here:  https://nhsconnect.github.io/gpconnect/appointments_use_case_search_for_free_slots.html

---
In line with 1.2.1 release note https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#appointment-management

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
