### ISSUE TITLE
Practitioner role & Delivery channel - Appointment resource

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#94]
1. Add Extension-GPConnect-DeliveryChannel-2 to GPConnect-Appointment-1 profile
2. Add Extension-GPConnect-PractitionerRole-1 extension to GPConnect-Appointment-1 profile.

Note these changes should affect the returned payload in the following calls -

Retrieve a patient's appointments
Read appointment
Book appointment
Amend appointment
Cancel appointment

---
In line with 1.2.1 release note  https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#appointment-management

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
