### ISSUE TITLE
If-Match header support for Amend and Cancel

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#95]
1. Ensure the If-Match header is supported and checked when passed for Amend and Cancel Appointment.
If the If-Match header is not passed by the consumer then the update should occur without it being checked.

(The demonstrator might do this already I'm not sure.)

---
In line with 1.2.1 release note  https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#appointment-management

**Comment by SimonFarrowNHS** [comment]
This functionality is implemented "for free" when using a hapi-fhir server, which is what the Demonstrator does.

**Comment by SimonFarrowNHS** [comment]
This functionality is implemented "for free" when using a hapi-fhir server, which is what the Demonstrator does.
