### ISSUE TITLE
Booking organisation in book appointment

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#96]
1. Ensure the demonstrator requires an ODS code in bookingOrganisation.identifier when book appointment is called.
The call should fail if it is not passed.

2. Ensure the demonstrator does not require but accepts bookingOrganisation.type when book appointment is called.
The call should NOT fail if either circumstance.

(it may already do this.)

---
In line with 1.2.1 release note  https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#appointment-management

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
