### ISSUE TITLE
Remove versionId from clinical resources

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#97]
1. Remove meta.versionId element from the following resources:

AllergyIntolerance
Medication
MedicationStatement
MedicationRequest
List
Bundle

(also remove meta.lastUpdated if still present)

---
In line with 1.2.1 release note: https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#access-record-structured

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
