### ISSUE TITLE
Bundle resource

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#98]
1. Order structured Bundle according to the diagram at:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_retrieve_patient_record.html#bundle-population-illustrated

---

In line with 1.2.1 release note https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#access-record-structured

**Comment by SimonFarrowNHS** [comment]
I consider this to be a somewhat perverse change since it would deliberately exclude detection of mandatory provider behaviour ie MUST be able to handle other orders.

**Comment by jonnyry** [comment]
Since the reference implementation is intended to mimic a real GP providing system.  However I understand your reasoning.  Happy to leave it as it is.

**Comment by KevinMayfield** [comment]
Shouldn't a receiver handle resources in a Bundle in any order? 
So it doesn't mater (except for Patient MUST be the first resource in the Bundle for this operation)

**Comment by jonnyry** [comment]
Correct, a Bundle can be in any order, including the Patient resource which can be anywhere in the Bundle; and consumers must be able to handle this.

However we asked providers to use a "sensible consistent order" to help developers and testers who need to inspect the FHIR JSON/XML payload, for testing or debugging purposes.

The intention was to align the GPC RI with the providers implementation.

**Comment by KevinMayfield** [comment]
I'd need to search the FHIR spec and it may only be part of FHIR messaging but I would suggest the primary resource is always first in search results.
[I'm saying this operation is a search because this operation is very similar to https://www.hl7.org/fhir/search.html#revinclude ]

**Comment by SimonFarrowNHS** [comment]
As per Jonny's response I am closing this issue.
