### ISSUE TITLE
Ensure search filter parameter for organisation type is using the correct code system

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#99]
1. We'd previously published the wrong URI for the organisation type search filter code system in the following table:

https://nhsconnect.github.io/gpconnect/appointments_use_case_search_for_free_slots.html#enhanced-slot-filtering

Ensure that the demonstrator is accepting the search filter using the new URI:

https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1

and not the old one:

https://fhir.nhs.uk/STU3/ValueSet/GPConnect-OrganisationType-1

---
In line with 1.2.1 release note https://nhsconnect.github.io/gpconnect/overview_release_notes_1_2_1.html#appointment-management

**Comment by SimonFarrowNHS** [comment]
Fixed at release/1.2.1
